"""empty message

Revision ID: 13af739d5eab
Revises: f63e2dc42180
Create Date: 2022-10-25 04:40:45.507700

"""
from alembic import op
import sqlalchemy as sa

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

# revision identifiers, used by Alembic.
revision = '13af739d5eab'
down_revision = 'f63e2dc42180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_incident_reporting', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.add_column(sa.Column('driver_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['driver_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_incident_reporting', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('driver_id')

    # ### end Alembic commands ###
