"""empty message

Revision ID: 36e0514f0d7d
Revises: 802609a71f7d
Create Date: 2022-10-06 02:06:53.372527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e0514f0d7d'
down_revision = '802609a71f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fleet_incident_reporting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver', sa.String(length=50), nullable=True),
    sa.Column('id_number_1', sa.Integer(), nullable=True),
    sa.Column('license_no_1', sa.Integer(), nullable=True),
    sa.Column('date_issued_1', sa.DateTime(), nullable=True),
    sa.Column('code_1', sa.String(length=50), nullable=True),
    sa.Column('endorsed_1', sa.String(length=50), nullable=True),
    sa.Column('do_you_have_your_own_insurance', sa.String(length=50), nullable=True),
    sa.Column('details_of_your_insurance', sa.String(length=100), nullable=True),
    sa.Column('details_of_previous_accidents', sa.String(length=100), nullable=True),
    sa.Column('registration_no_1', sa.Integer(), nullable=True),
    sa.Column('milage', sa.Integer(), nullable=True),
    sa.Column('make_1', sa.String(length=50), nullable=True),
    sa.Column('model_1', sa.String(length=50), nullable=True),
    sa.Column('reason_for_passenger_in_vehicle', sa.String(length=50), nullable=True),
    sa.Column('is_the_passenger_a_employee', sa.String(length=50), nullable=True),
    sa.Column('name_surname_of_passenger', sa.String(length=50), nullable=True),
    sa.Column('id_no_attach_copy_of_id', sa.Integer(), nullable=True),
    sa.Column('address_1', sa.String(length=100), nullable=True),
    sa.Column('details_of_injury_is', sa.String(length=100), nullable=True),
    sa.Column('names_and_surname_of_driver', sa.String(length=50), nullable=True),
    sa.Column('contact_details', sa.String(length=100), nullable=True),
    sa.Column('id_number_2', sa.Integer(), nullable=True),
    sa.Column('license_no_2', sa.Integer(), nullable=True),
    sa.Column('date_issued', sa.DateTime(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('endorsed', sa.String(length=50), nullable=True),
    sa.Column('address_2', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=50), nullable=True),
    sa.Column('company_address', sa.String(length=100), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('telephone_no', sa.Integer(), nullable=True),
    sa.Column('email_address', sa.String(length=50), nullable=True),
    sa.Column('registration_no_2', sa.Integer(), nullable=True),
    sa.Column('make_2', sa.String(length=50), nullable=True),
    sa.Column('model_2', sa.String(length=50), nullable=True),
    sa.Column('registration_no', sa.Integer(), nullable=True),
    sa.Column('colour', sa.String(length=50), nullable=True),
    sa.Column('make', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('details_of', sa.String(length=100), nullable=True),
    sa.Column('saps_case_no', sa.Integer(), nullable=True),
    sa.Column('take_photo_1', sa.String(length=50), nullable=True),
    sa.Column('take_photo_2', sa.String(length=50), nullable=True),
    sa.Column('manager_1', sa.String(length=50), nullable=True),
    sa.Column('date_1', sa.DateTime(), nullable=True),
    sa.Column('time_1', sa.String(length=50), nullable=True),
    sa.Column('manager_2', sa.String(length=50), nullable=True),
    sa.Column('date_2', sa.DateTime(), nullable=True),
    sa.Column('time_2', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fleet_incident_reporting')
    # ### end Alembic commands ###
