"""empty message

Revision ID: 36f07a7ccd3b
Revises: 4757f431c9b0
Create Date: 2022-10-06 23:49:14.753938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f07a7ccd3b'
down_revision = '4757f431c9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fleet_inspection_card_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_1', sa.DateTime(), nullable=True),
    sa.Column('time_1', sa.String(length=50), nullable=True),
    sa.Column('registration_1', sa.Integer(), nullable=True),
    sa.Column('fleet', sa.Integer(), nullable=True),
    sa.Column('milage_1', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('f_name', sa.String(length=50), nullable=True),
    sa.Column('contact_2', sa.String(length=100), nullable=True),
    sa.Column('yes', sa.String(length=50), nullable=True),
    sa.Column('yes_2', sa.String(length=50), nullable=True),
    sa.Column('yes_3', sa.String(length=50), nullable=True),
    sa.Column('yes_4', sa.String(length=50), nullable=True),
    sa.Column('yes_5', sa.String(length=50), nullable=True),
    sa.Column('yes_6', sa.String(length=50), nullable=True),
    sa.Column('text_1', sa.String(length=100), nullable=True),
    sa.Column('text_2', sa.String(length=100), nullable=True),
    sa.Column('current_milage', sa.String(length=50), nullable=True),
    sa.Column('average', sa.String(length=50), nullable=True),
    sa.Column('order', sa.String(length=50), nullable=True),
    sa.Column('wheel', sa.String(length=50), nullable=True),
    sa.Column('last_service', sa.DateTime(), nullable=True),
    sa.Column('km', sa.String(length=50), nullable=True),
    sa.Column('intervals', sa.String(length=50), nullable=True),
    sa.Column('next_service', sa.String(length=50), nullable=True),
    sa.Column('vehicle_2', sa.String(length=100), nullable=True),
    sa.Column('tools', sa.String(length=100), nullable=True),
    sa.Column('defaults', sa.String(length=100), nullable=True),
    sa.Column('current_2', sa.String(length=50), nullable=True),
    sa.Column('current_sign_time', sa.DateTime(), nullable=True),
    sa.Column('current_time', sa.String(length=50), nullable=True),
    sa.Column('new_driver', sa.String(length=50), nullable=True),
    sa.Column('date_2', sa.DateTime(), nullable=True),
    sa.Column('time_2', sa.String(length=50), nullable=True),
    sa.Column('person', sa.String(length=100), nullable=True),
    sa.Column('date_3', sa.DateTime(), nullable=True),
    sa.Column('time_3', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fleet_nc_incident_reporting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_no', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_nc_incident_reporting', schema=None) as batch_op:
        batch_op.drop_column('registration_no')

    op.drop_table('fleet_inspection_card_form')
    # ### end Alembic commands ###
