"""empty message

Revision ID: 4757f431c9b0
Revises: f83f8bba7de1
Create Date: 2022-10-06 06:08:54.861441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4757f431c9b0'
down_revision = 'f83f8bba7de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fleet_nc_incident_reporting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(length=50), nullable=True),
    sa.Column('vehicle_manufacturer', sa.String(length=50), nullable=True),
    sa.Column('License', sa.Integer(), nullable=True),
    sa.Column('date_issued', sa.DateTime(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('endorsed', sa.String(length=50), nullable=True),
    sa.Column('License_2', sa.Integer(), nullable=True),
    sa.Column('date_issued_2', sa.DateTime(), nullable=True),
    sa.Column('Code_2', sa.Integer(), nullable=True),
    sa.Column('endorsed_2', sa.String(length=50), nullable=True),
    sa.Column('demage', sa.String(length=50), nullable=True),
    sa.Column('demage_2', sa.String(length=50), nullable=True),
    sa.Column('yes_no', sa.String(length=50), nullable=True),
    sa.Column('manager', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('time', sa.String(length=50), nullable=True),
    sa.Column('yes_no_2', sa.String(length=50), nullable=True),
    sa.Column('manager_2', sa.String(length=50), nullable=True),
    sa.Column('date_2', sa.DateTime(), nullable=True),
    sa.Column('time_2', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fleet_nc_incident_reporting')
    # ### end Alembic commands ###
