"""empty message

Revision ID: 4f3451639b8b
Revises: 8febb29fa30a
Create Date: 2022-10-12 18:13:55.899311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f3451639b8b'
down_revision = '8febb29fa30a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_expense', schema=None) as batch_op:
        batch_op.drop_column('added_on')

    # ### end Alembic commands ###
