"""empty message

Revision ID: 6a44712799fb
Revises: 687691603e38
Create Date: 2022-10-07 00:54:07.863928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a44712799fb'
down_revision = '687691603e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_inspection_card_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_driver', sa.String(length=50), nullable=True))
        batch_op.drop_column('current_2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_inspection_card_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_2', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('current_driver')

    # ### end Alembic commands ###
