"""empty message

Revision ID: 8febb29fa30a
Revises: fa52713e1f17
Create Date: 2022-10-11 21:49:12.163982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8febb29fa30a'
down_revision = 'fa52713e1f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuel_value', sa.Integer(), nullable=True),
    sa.Column('oil_value', sa.Integer(), nullable=True),
    sa.Column('repair_and_maint', sa.Integer(), nullable=True),
    sa.Column('tyre_value', sa.Integer(), nullable=True),
    sa.Column('accident_value', sa.Integer(), nullable=True),
    sa.Column('other_value', sa.Integer(), nullable=True),
    sa.Column('toll_value', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_expense')
    # ### end Alembic commands ###
