"""empty message

Revision ID: cb76f9185f3a
Revises: f560be6cbdc1
Create Date: 2022-10-26 00:52:35.610537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb76f9185f3a'
down_revision = 'f560be6cbdc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_nc_incident_reporting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_fleet_nc_incident_reporting_driver_id_user'), 'user', ['driver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_nc_incident_reporting', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_fleet_nc_incident_reporting_driver_id_user'), type_='foreignkey')
        batch_op.drop_column('driver_id')

    # ### end Alembic commands ###
