"""empty message

Revision ID: cf75de5edf9c
Revises: 386448c20a52
Create Date: 2022-10-26 01:42:42.387269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf75de5edf9c'
down_revision = '386448c20a52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_nc_incident_reporting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accident_value', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('details_of_demage', sa.String(length=500), nullable=True))
        batch_op.drop_column('demage')
        batch_op.drop_column('demage_2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_nc_incident_reporting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('demage_2', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('demage', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('details_of_demage')
        batch_op.drop_column('accident_value')

    # ### end Alembic commands ###
