"""empty message

Revision ID: ec2617bdf7c7
Revises: 9c36a60d6e61
Create Date: 2022-10-07 04:17:50.719539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec2617bdf7c7'
down_revision = '9c36a60d6e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_nc_incident_reporting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_licence_date_issued', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('driver_licence_date_issued_2', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reporting_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reporting_date_2', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_issued_2')
        batch_op.drop_column('date_issued')
        batch_op.drop_column('date')
        batch_op.drop_column('date_2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_nc_incident_reporting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_2', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('date_issued', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('date_issued_2', sa.DATETIME(), nullable=True))
        batch_op.drop_column('reporting_date_2')
        batch_op.drop_column('reporting_date')
        batch_op.drop_column('driver_licence_date_issued_2')
        batch_op.drop_column('driver_licence_date_issued')

    # ### end Alembic commands ###
