"""empty message

Revision ID: f560be6cbdc1
Revises: 13af739d5eab
Create Date: 2022-10-25 05:04:49.622611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f560be6cbdc1'
down_revision = '13af739d5eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_card', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_fleet_card_driver_id'), ['driver_id'])

    with op.batch_alter_table('fleet_incident_reporting', schema=None) as batch_op:
        batch_op.drop_constraint('fk_fleet_incident_reporting_driver_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_fleet_incident_reporting_driver_id_user'), 'user', ['driver_id'], ['id'])

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_vehicle_driver_id'), ['driver_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_vehicle_driver_id'), type_='unique')

    with op.batch_alter_table('fleet_incident_reporting', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_fleet_incident_reporting_driver_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_fleet_incident_reporting_driver_id_user', 'user', ['driver_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('fleet_card', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_fleet_card_driver_id'), type_='unique')

    # ### end Alembic commands ###
