"""empty message

Revision ID: f63e2dc42180
Revises: 4f3451639b8b
Create Date: 2022-10-25 02:58:56.227847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f63e2dc42180'
down_revision = '4f3451639b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_incident_reporting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_incident_reporting', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
