"""empty message

Revision ID: fa52713e1f17
Revises: 5f1582466f62
Create Date: 2022-10-11 21:16:39.430270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa52713e1f17'
down_revision = '5f1582466f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuel_value', sa.String(length=50), nullable=True),
    sa.Column('oil_value', sa.String(length=50), nullable=True),
    sa.Column('repair_and_maint', sa.String(length=50), nullable=True),
    sa.Column('tyre_value', sa.String(length=50), nullable=True),
    sa.Column('accident_value', sa.String(length=50), nullable=True),
    sa.Column('other_value', sa.String(length=50), nullable=True),
    sa.Column('toll_value', sa.String(length=50), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_expense')
    # ### end Alembic commands ###
