"""initilizing the database

Revision ID: 38d7053dd9ff
Revises: 
Create Date: 2022-08-12 17:31:27.051890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d7053dd9ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=True),
    sa.Column('joining_date', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=400), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('registration_no', sa.Integer(), nullable=True),
    sa.Column('fleet_no', sa.Integer(), nullable=True),
    sa.Column('milage', sa.Integer(), nullable=True),
    sa.Column('driver_license_image', sa.String(length=200), nullable=True),
    sa.Column('id_no_image', sa.String(length=200), nullable=True),
    sa.Column('drivers_license_no', sa.Integer(), nullable=True),
    sa.Column('drivers_license_endorced', sa.String(length=5), nullable=True),
    sa.Column('drivers_license_renewal_date', sa.Date(), nullable=True),
    sa.Column('cell_no', sa.Integer(), nullable=True),
    sa.Column('family_members', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_no', sa.Integer(), nullable=False),
    sa.Column('financer', sa.String(length=100), nullable=False),
    sa.Column('account_no', sa.Integer(), nullable=False),
    sa.Column('original_capital_balance', sa.Integer(), nullable=False),
    sa.Column('installment_amount', sa.Integer(), nullable=False),
    sa.Column('frequency_of_installment', sa.Integer(), nullable=False),
    sa.Column('date_commenced', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('original_term', sa.Integer(), nullable=False),
    sa.Column('remaining_installments', sa.Integer(), nullable=False),
    sa.Column('balloon_risidual', sa.String(length=100), nullable=False),
    sa.Column('outstanding_capital_balance', sa.Integer(), nullable=False),
    sa.Column('advance_amount', sa.Integer(), nullable=False),
    sa.Column('actual_contract_balance', sa.Integer(), nullable=False),
    sa.Column('interest_rate', sa.Integer(), nullable=False),
    sa.Column('take_on_odo', sa.String(length=100), nullable=False),
    sa.Column('vehicle_manufacturer', sa.String(length=100), nullable=False),
    sa.Column('date_of_first_registration', sa.Date(), nullable=True),
    sa.Column('model', sa.String(length=25), nullable=False),
    sa.Column('color', sa.String(length=25), nullable=False),
    sa.Column('mobile_number', sa.Integer(), nullable=True),
    sa.Column('engine_no', sa.String(length=50), nullable=False),
    sa.Column('vin_no', sa.String(length=50), nullable=False),
    sa.Column('tank_capacity', sa.String(length=50), nullable=False),
    sa.Column('license_disk_expiry_date', sa.Date(), nullable=True),
    sa.Column('license_disk_renewal_date', sa.Date(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id')
    )
    op.create_table('vehicle_expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuel_value', sa.String(length=50), nullable=True),
    sa.Column('oil_value', sa.String(length=50), nullable=True),
    sa.Column('repair_and_maint', sa.String(length=50), nullable=True),
    sa.Column('tyre_value', sa.String(length=50), nullable=True),
    sa.Column('accident_value', sa.String(length=50), nullable=True),
    sa.Column('other_value', sa.String(length=50), nullable=True),
    sa.Column('toll_value', sa.String(length=50), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_expense')
    op.drop_table('vehicle')
    op.drop_table('user')
    # ### end Alembic commands ###
