"""empty message

Revision ID: 9c36a60d6e61
Revises: 6a44712799fb
Create Date: 2022-10-07 03:34:38.475166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c36a60d6e61'
down_revision = '6a44712799fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_inspection_card_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_current_driver_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('current_sign_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('signature_new_driver_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('signature_inspaction_person_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('current_time')
        batch_op.drop_column('date_2')
        batch_op.drop_column('date_3')
        batch_op.drop_column('current_sign_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_inspection_card_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_sign_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('date_3', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('date_2', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('current_time', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('signature_inspaction_person_date')
        batch_op.drop_column('signature_new_driver_date')
        batch_op.drop_column('current_sign_time')
        batch_op.drop_column('signature_current_driver_date')

    # ### end Alembic commands ###
