"""empty message

Revision ID: a3d711890d76
Revises: ec2617bdf7c7
Create Date: 2022-10-07 04:37:56.176652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d711890d76'
down_revision = 'ec2617bdf7c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_incident_reporting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_licencse_date_issued_1', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('driver_license_date_issued_2', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reporting_date_1', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reporting_date_2', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_2')
        batch_op.drop_column('date_1')
        batch_op.drop_column('date_issued')
        batch_op.drop_column('date_issued_1')

    with op.batch_alter_table('maintenances_tyres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maintenance_expiry_year_month_km_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('maintenance_expiry_year_month_km')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenances_tyres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maintenance_expiry_year_month_km', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('maintenance_expiry_year_month_km_date')

    with op.batch_alter_table('fleet_incident_reporting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_issued_1', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('date_issued', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('date_1', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('date_2', sa.DATETIME(), nullable=True))
        batch_op.drop_column('reporting_date_2')
        batch_op.drop_column('reporting_date_1')
        batch_op.drop_column('driver_license_date_issued_2')
        batch_op.drop_column('driver_licencse_date_issued_1')

    # ### end Alembic commands ###
