"""Adding FleetCard table with relationship of driver

Revision ID: bfdbfe488b17
Revises: 20f4a3511942
Create Date: 2022-08-20 19:01:29.025154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfdbfe488b17'
down_revision = '20f4a3511942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fleet_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_no', sa.String(length=50), nullable=True),
    sa.Column('driver', sa.String(length=60), nullable=True),
    sa.Column('take_on_odo', sa.String(length=100), nullable=True),
    sa.Column('vehicle_manufacturer', sa.String(length=100), nullable=True),
    sa.Column('date_of_first_registration', sa.Date(), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('engine_no', sa.String(length=50), nullable=True),
    sa.Column('vin_no', sa.String(length=50), nullable=True),
    sa.Column('tank_capacity', sa.String(length=50), nullable=True),
    sa.Column('employee_no', sa.String(length=50), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fleet_card')
    # ### end Alembic commands ###
