"""empty message

Revision ID: f83f8bba7de1
Revises: 36e0514f0d7d
Create Date: 2022-10-06 03:41:52.941709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83f8bba7de1'
down_revision = '36e0514f0d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_incident_reporting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colour_1', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('registration_no_3', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('colour_2', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('make_3', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('model_3', sa.String(length=50), nullable=True))
        batch_op.drop_column('registration_no')
        batch_op.drop_column('make')
        batch_op.drop_column('colour')
        batch_op.drop_column('model')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fleet_incident_reporting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('colour', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('make', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('registration_no', sa.INTEGER(), nullable=True))
        batch_op.drop_column('model_3')
        batch_op.drop_column('make_3')
        batch_op.drop_column('colour_2')
        batch_op.drop_column('registration_no_3')
        batch_op.drop_column('colour_1')

    # ### end Alembic commands ###
